apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-vila
  labels:
    app: db
spec:
  containers:
  - name: postgres-vila
    image: vila_db:1.0
    ports:
      - containerPort: 5432
